# Generated by Django 5.2.2 on 2025-06-07 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g. Casual Summer Look', max_length=100)),
                ('occasion', models.CharField(blank=True, max_length=100, null=True)),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('spring', 'Spring'), ('autumn', 'Autumn'), ('all', 'All Season')], max_length=20)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g. White T-shirt, Denim Jacket', max_length=100)),
                ('category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('dress', 'Dress'), ('outerwear', 'Outerwear'), ('sportswear', 'Sportswear'), ('specialized', 'Specialized'), ('footwear', 'Footwear'), ('accessory', 'Accessory'), ('other', 'Other')], max_length=50)),
                ('color', models.CharField(help_text='E.g. Red, Black, Navy Blue', max_length=30)),
                ('image', models.ImageField(upload_to='wardrobe/')),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('spring', 'Spring'), ('autumn', 'Autumn'), ('all', 'All Season')], default='all', max_length=20)),
                ('style_tags', models.JSONField(blank=True, help_text="AI-generated tags like 'casual', 'formal', etc.", null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('linked_products', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('outfit_matches', models.ManyToManyField(blank=True, to='app.outfit')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='outfit',
            name='items',
            field=models.ManyToManyField(to='app.wardrobeitem'),
        ),
    ]
