# Generated by Django 5.2.2 on 2025-06-09 10:54

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobeitem',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='wardrobe/'),
        ),
    ]
