# Generated by Django 5.2.2 on 2025-06-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardrobeitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='layer',
            field=models.CharField(blank=True, choices=[('base', 'Base Layer'), ('mid', 'Mid Layer'), ('outer', 'Outer Layer')], help_text='Used to build layer-aware outfits', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='occasions',
            field=models.JSONField(blank=True, help_text="E.g. ['wedding', 'office', 'casual weekend']", null=True),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='pattern',
            field=models.CharField(blank=True, help_text='E.g. striped, plain, floral', max_length=50, null=True),
        ),
    ]
