version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: modella_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - modella_network

volumes:
  redis_data:
    name: modella_redis_data

networks:
  wardrobe_network:
    name: modella_network 